FROM node:18-bullseye

WORKDIR /usr/src/app

COPY front/package*.json ./


RUN npm install -g @angular/cli@18 --no-progress --loglevel=error && \
    npm install --no-progress --omit=optional --loglevel=error

COPY front/. /usr/src/app

EXPOSE 4200 49153


CMD [ "npm", "start" ]