# Phase de Build avec Java 21
FROM maven:3.8-eclipse-temurin-21 AS build

WORKDIR /app

COPY back/pom.xml .

RUN mvn dependency:go-offline

COPY back/src ./src

RUN mvn clean package -DskipTests

# Phase Execution avec Java 21
FROM eclipse-temurin:21-jdk-jammy

WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]