version: '3.8'

services:
  database:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=alten_shop
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  back_app:
    build:
      context: .
      dockerfile: dockerfile-back
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/alten_shop
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_PROFILES_ACTIVE=dev 
    volumes:
      - ./back/src:/app/src
      - ./back/pom.xml:/app/pom.xml
    networks:
      - app-network
    restart: on-failure

  front_app:
    build:
      context: .
      dockerfile: dockerfile-front
    ports:
      - "4200:4200"
    volumes:
      - ./front:/usr/src/app
      - /usr/src/app/node_modules

    environment:
      - NODE_ENV=development
      - API_URL=http://localhost:8080
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
    ports:
      - "8081:80"
    depends_on:
      - database
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge



